apiVersion: v1
kind: ConfigMap
metadata:                      
    name: simple-conf
    namespace: prac
data:
    # property-like keys; each key maps to a simple value
    us_name: kalpesh
    # file-like keys
    multiprop: |
        conf-mgmt: ansible
        iaac: terraform
        cloud: aws

---
apiVersion: v1
kind: Namespace
metadata: 
    name: prac