apiVersion: v1
kind: Namespace
metadata:
  name: prac            
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev
  namespace: prac


# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mon
  namespace: prac
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]

# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moniter
  namespace: prac
subjects:
- kind: ServiceAccount
  name: dev
  namespace: prac
roleRef:
  kind: Role
  name: mon
  apiGroup: rbac.authorization.k8s.io

---
# kubectl auth can-i list pods/log --namespace prac --as system:serviceaccount:prac:dev
#command to check permissions
#kubectl get clusterrole cluster-admin -o yaml > cls.yaml
