apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {   "access" : "proxy",
                "editable" : "true",
                "name": "mysql",
                "type": "mysql",
                "url": "10.1.1.96:6603",
                "database": "bgc_chitale",
                "user": "dbuser1",
                "password" : "Vinayak123#",
                "version": 1

             }
        ]
    }
