apiVersion: v1
kind: ConfigMap
metadata: 
  name: conf-2
  namespace: prac
data: 
  user_name: kalpesh
  skill: |
    dev: aws
    dev1: linux

---
apiVersion: v1
kind: Pod
metadata: 
  name: conf-two
  namespace: prac
spec:
  containers: 
    - name: conf2-demo
      image: alpine
      command: ["sleep","3600"]
      env:
        - name: conf2
          valueFrom:
            configMapKeyRef: 
              name: conf-2
              key: user_name
        - name: conf2-skill
          valueFrom: 
            configMapKeyRef: 
              name: conf-2
              key: skill