apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring 
spec:
  dnsNames:
    - 10.1.1.135
    - 10.1.1.136 
  secretName: grafana
  issuerRef:
    name: grafana
