# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moniter
  namespace: prac
subjects:
- kind: ServiceAccount
  name: dev # Name is case sensitive
  namespace: prac
roleRef:
  kind: Role
  name: mon
  apiGroup: rbac.authorization.k8s.io
---
